module.exports = {
  ROLES: ["ADMIN", "MANAGER", "DRIVER", "VIEWER"],
  VEHICLE_STATUS: ["AVAILABLE", "IN_USE", "MAINTENANCE", "OUT_OF_SERVICE"],
  TRIP_STATUS: ["PENDING", "ACTIVE", "COMPLETED", "CANCELLED"],
  MAINTENANCE_STATUS: ["SCHEDULED", "IN_PROGRESS", "COMPLETED", "OVERDUE"],
  API_MESSAGES: {
    SUCCESS: "Success",
    ERROR: "Error",
    NOT_FOUND: "Not found",
  },
};
